spring:
  datasource:
    # [ ] << 대괄호는 빼면됨
    url: jdbc:mysql://localhost:3306/ssg_tyranno?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ssg_tyranno
    password: 1234
    
  profiles:
<<<<<<< HEAD
    default: local
=======
    default: aws


>>>>>>> develop
