spring:
  datasource:
    #    url: jdbc:mysql://15.164.246.181:3306/tyranno_local?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/ssg_tyranno?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8

    username: ssg_tyranno
    password: 1234

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  security:
    user:
      name: tyranno
      password: xlfksh97
# swagger
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /api-docs
# jwt
JWT:
  HEADER: Authorization
  SECRET_KEY: 395c0719ce36e1fe04e4a6e4386f97735a18bec33f73b8d8d65adc188697dfe795bfa81a7f59a777704d1f8b9ce1baa99dad4c670d75be52efc4bfa7d9c39db5
  EXPIRATION_TIME: 86400