spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssgdb
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # creat ?? db ??? ? ???
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MYSQL5InnoDBDialect
        format_sql: true

JWT:
  secret-key: ssg
  access-token-expiration: 30000
  # refresh-token-expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
